name: Build Stubs
on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day; adjust as necessary
  workflow_dispatch:
    inputs:
      tag:
        description: 'Blender Version Tag (e.g., v4.0.1)'
        required: false

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.check.outputs.new_tag }}
      new_commit: ${{ steps.check.outputs.new_commit }}
      tag_input: ${{ steps.set_tag_input.outputs.tag_input }}
      python_version: ${{ steps.set_python_version.outputs.python_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check latest tag and commit
        id: check
        if: ${{ github.event.inputs.tag == '' }}
        run: python ./workspace/check_latest.py

      - name: Set tag input
        id: set_tag_input
        run: |
          if [[ "${{ github.event.inputs.tag }}" != '' ]]; then
            echo "tag_input=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
            echo "Building for ${{ github.event.inputs.tag }}"
          elif [[ "${{ steps.check.outputs.new_tag }}" == 'true' ]]; then
            echo "tag_input=${{ steps.check.outputs.latest_tag }}" >> $GITHUB_OUTPUT
            echo "Building for ${{ steps.check.outputs.latest_tag }}"
          elif [[ "${{ steps.check.outputs.new_commit }}" == 'true' ]]; then
            echo "tag_input=main" >> $GITHUB_OUTPUT
            echo "Building for main"
          fi
        

      - name: Set Python version
        id: set_python_version
        run: |
          if [[ "${{ steps.set_tag_input.outputs.tag_input }}" == v3.* ]] || [[ "${{ steps.set_tag_input.outputs.tag_input }}" == v4.0.* ]]; then
            echo "python_version=3.10.11" >> $GITHUB_OUTPUT
            echo "Building for Python 3.10.11"
          else
            echo "python_version=3.11.6" >> $GITHUB_OUTPUT
            echo "Building for Python 3.11.6"
          fi


  generate-stubs:
    needs: check-version
    if: ${{ needs.check-version.outputs.tag_input != '' }}
    uses: ./.github/workflows/generate_stubs.yml
    with:
      tag: ${{ needs.check-version.outputs.tag_input }} 
      python_version: ${{ needs.check-version.outputs.python_version }}

