name: Build bpy for macOS

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Blender Tag to build'
        required: true

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout Blender repository recursively
        uses: actions/checkout@v2
        with:
          repository: blender/blender
          ref: ${{ github.event.inputs.tag }}
          submodules: 'recursive'
          path: blender 


      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.10.13
          activate-environment: bpy-env
          channels: conda-forge
          miniconda-version: "latest" 

      - name: Install Conda Dependencies
        run: |
          conda install -y setuptools -c conda-forge

      - name: Add conda subdirectories to PATH
        run: |
          for dir in $(find /Users/runner/conda_pkgs_dir/ -mindepth 1 -type d); do
            echo "$dir" >> $GITHUB_PATH
          done


      - name: Install  dependencies
        run: |
          brew install cmake subversion

      - name: Cache Blender dependencies
        uses: actions/cache@v2
        with:
          path: |
            ./lib
          key: ${{ runner.os }}-blender-deps-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-blender-deps-

          
      # - name: Install Cuda Toolkit
      #   uses: Jimver/cuda-toolkit@v0.2.11
      #   id: cuda-toolkit
      #   with:
      #     cuda: '12.1.0'


      - name: Cache build files (for testing only)
        uses: actions/cache@v2
        with:
          path: |
            ./build_linux_bpy
          key: ${{ runner.os }}-blender-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-blender-build-


      - name: Build Blender
        run: |
          cd ./blender
          make update
          make bpy


      # - name: Setup terminal session
      #   uses: fawazahmed0/action-debug@main
      #   with:
      #       credentials: "user:p@ss!"


      - name: Install Blender
        run: |
          cd ./blender
          echo "SITE_PACKAGES=`python -c 'import site; print(site.getsitepackages()[0])'`" >> $GITHUB_ENV
          cp -r ./build_darwin_bpy/bin/bpy $SITE_PACKAGES

      - name: Install docs prereqs and generate API Docs
        run: |
          pip install bpystubgen
          cd ./blender
          python ./doc/python_api/sphinx_doc_gen.py -- --output=../python_api
          python -m bpystubgen ../python_api/sphinx-in ../python_api/output

      - name: Copy BPY Stubs to bin folder
        run: |
          cp -R ./python_api/output/*  ./build_darwin_bpy/bin/


      - name: Make Wheel
        run: |
          python ./blender/build_files/utils/make_bpy_wheel.py ./build_darwin_bpy/bin/

      - name: Upload Wheel as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bpy-macos
          path: |
            ./build_darwin_bpy/bin/*.whl
