name: Generate Blender Python API Stubs

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Blender Version Tag (e.g., v4.0.1)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.x'

      - name: Download Blender
        run: |
          wget https://download.blender.org/release/${{ github.event.inputs.tag }}/blender-${{ github.event.inputs.tag:1 }}-linux-x64.tar.xz
          tar -xf blender-${{ github.event.inputs.tag:1 }}-linux-x64.tar.xz
          mv blender-${{ github.event.inputs.tag:1 }}-linux-x64 blender

      - name: Install Documentation Prerequisites
        run: |
          pip install bpystubgen

      - name: Generate API Docs and Stubs
        run: |
          cd blender
          ./blender --background --factory-startup -noaudio --python doc/python_api/sphinx_doc_gen.py -- --output=../python_api
          python -m bpystubgen ../python_api/sphinx-in ../python_api/output

      - name: Upload Stubs as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: blender-python-api-stubs-${{ github.event.inputs.tag}}
          path: |
            python_api/output/**
