name: Update Python Package Repository Index

on:
  release:
    types: [created, edited]
  push:
    branches:
      - main
  workflow_dispatch:
  

jobs:
  update-package-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Create gh-pages branch if it doesn't exist
        run: |
          if ! git ls-remote --heads origin gh-pages; then
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "chore: initial gh-pages commit"
            git push origin gh-pages
            git checkout main
          fi


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install typer PyGithub

      - name: Generate Repository Index
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python ./workspace/generate_package_index.py ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }}

      - name: Commit and Push
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Update package index'
          add: 'docs/'
          branch: 'gh-pages'  # Change to your GitHub Pages branch
