name: Update Python Package Repository Index

on:
  release:
    types: [created, edited]
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  update-package-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install typer PyGithub

      - name: Generate Repository Index on Main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python ./main/workspace/generate_package_index.py ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }}

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          

      - name: Copy Index to gh-pages Branch
        run: |
          cp -r ./main/docs/* ./
      
      - name: Commit and Push to gh-pages
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: github-actions[bot]@users.noreply.github.com
          message: 'Update package index'
          add: '.'
          branch: 'gh-pages'
          token: ${{ secrets.GITHUB_TOKEN }}
